AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Task Definition for goep.dev prod

Parameters:
  AWSAccountId:
    Type: String
    Description: Your AWS account ID

Resources:
  GoepDevProdTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: goep-dev-prod-task
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWSAccountId}:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: goep-dev-prod-container
          Image: !Sub "${AWSAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/goep-dev-prod:prod-latest"
          PortMappings:
            - ContainerPort: 3000
