AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Task Definition for goep.dev nonprod

Parameters:
  AWSAccountId:
    Type: String
    Description: Your AWS account ID

Resources:
  GoepDevNonprodTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: goep-dev-nonprod-task
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWSAccountId}:role/ecsTaskExecutionRole"
      ContainerDefinitions:
        - Name: goep-dev-nonprod-container
          Image: !Sub "${AWSAccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/goep-dev-nonprod:nonprod-latest"
          PortMappings:
            - ContainerPort: 3000
