AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate Service for goep.dev Nonprod

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  ClusterName:
    Type: String
  TargetGroupArn:
    Type: String
  AlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The security group ID of the Application Load Balancer

Resources:
  GoepDevNonprodService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: goep-dev-nonprod-service
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: goep-dev-nonprod-task
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref NonprodServiceSG
      LoadBalancers:
        - ContainerName: goep-dev-nonprod-container
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroupArn

  NonprodServiceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ALB to reach ECS task on port 3000
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref AlbSecurityGroupId
